# Generated by Django 5.2.9 on 2025-12-15 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='especialidad',
            name='nombre',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
