# Generated by Django 5.2.9 on 2025-12-15 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnos', '0002_alter_especialidad_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='apellido',
            field=models.CharField(default='-', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='paciente',
            name='email',
            field=models.EmailField(default='-', max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='paciente',
            name='telefono',
            field=models.CharField(default='-', max_length=20),
            preserve_default=False,
        ),
    ]
